/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

//import com.xinxi_Action.struts.action.bean.Modle;
import com.xinxi_Action.struts.form.OlympicgamesproductContentUpdateDeleteForm;
//import com.xinxi_Action.struts.form.ProductUpdateDeleteForm;
import com.xinxi_Action.struts.session.SessionService;
import com.xinxi_Action.struts.session.StaticName;
import com.web_interface.fenye.FenyeSelectInterface;
import com.web_serializable_bean.fenye_bean.Fenye;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * 2008/6/08 whp V_1.00
 * 2008/9/08 李永杰 V_1.01
 *
 */
public class OlympicgamesproductContentUpdateDeleteAction extends
		DispatchAction {

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	private static final Log log = LogFactory
			.getLog(ProductUpdateDeleteAction.class);

	public ActionForward updateok(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		log.debug("---LoginDAO loginCheck---");
		// 设置session判断用户是否成功登陆或者关闭网页后复制url来进行访问
		// 测试页面跳转 成功=OK
		OlympicgamesproductContentUpdateDeleteForm olympicgamesproductContentUpdateDeleteForm = (OlympicgamesproductContentUpdateDeleteForm) form;
		HttpSession session = request.getSession();
		SessionService sessionservice = new SessionService();
		boolean booleanUser = sessionservice.SessionService(session,
				StaticName.USERLOGIN = (String) session.getAttribute("login"));
		//List<Fenye> update = new ArrayList<Fenye>();
		//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>李永杰 V_1.0>>>start>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
		if (booleanUser) {
			FenyeSelectInterface updateService = getOlympicgamesUpdateInterface();
			updateService.Olympicgames_update(olympicgamesproductContentUpdateDeleteForm);//修改奥运新闻
			System.out.println("奥运新闻修改成功!!!!!!!");
			return mapping.findForward("olympicgamesok");
		//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>李永杰 V_1.0>>>end>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
		}
		return mapping.findForward("olympicgamesok");
	}

	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		log.debug("---LoginDAO loginCheck---");
		// 设置session判断用户是否成功登陆或者关闭网页后复制url来进行访问
		// 测试页面跳转 成功=OK
		OlympicgamesproductContentUpdateDeleteForm olympicgamesproductContentUpdateDeleteForm = (OlympicgamesproductContentUpdateDeleteForm) form;
		HttpSession session = request.getSession();
		SessionService sessionservice = new SessionService();
		boolean booleanUser = sessionservice.SessionService(session,
				StaticName.USERLOGIN = (String) session.getAttribute("login"));
		List<Fenye> update = new ArrayList<Fenye>();

		if (booleanUser) {
			
			System.out.println("update修改页面:1");

			update.add(new Fenye(olympicgamesproductContentUpdateDeleteForm
					.getFenye_Id(), olympicgamesproductContentUpdateDeleteForm
					.getZhuti(), olympicgamesproductContentUpdateDeleteForm
					.getZuozhe(), olympicgamesproductContentUpdateDeleteForm
					.getFwjilu()));
			request.setAttribute("productupdate", update);
			return mapping.findForward("aoyunupdate");
		}

		return mapping.findForward("aoyunupdate");

	}

	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		log.debug("---LoginDAO loginCheck---");
		// 设置session判断用户是否成功登陆或者关闭网页后复制url来进行访问
		// 测试页面跳转 成功=OK
		OlympicgamesproductContentUpdateDeleteForm olympicgamesproductContentUpdateDeleteForm = (OlympicgamesproductContentUpdateDeleteForm) form;
		System.out.println("----------------------------------------");
		System.out.println(olympicgamesproductContentUpdateDeleteForm.getFenye_Id());
		System.out.println("----------------------------------------");
		HttpSession session = request.getSession();
		SessionService sessionservice = new SessionService();
		boolean booleanUser = sessionservice.SessionService(session,
				StaticName.USERLOGIN = (String) session.getAttribute("login"));
		//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>李永杰 V_1.0>>>start>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
		if (booleanUser) {
			FenyeSelectInterface updateService = getOlympicgamesUpdateInterface();
			String fenye_Id = request.getParameter("fenye_Id");//获取奥运新闻编号
			updateService.Olympicgames_delete(Integer.parseInt(fenye_Id));//删除奥运新闻
			return mapping.findForward("olympicgamesok");
			//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>李永杰 V_1.0>>>end>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
		}
		return mapping.findForward("olympicgamesok");
		
	}

	// private FenyeSelectInterface getProductDeleteInterface() {
	// ApplicationContext appContext = WebApplicationContextUtils
	// .getWebApplicationContext(this.getServlet().getServletContext());
	// return (FenyeSelectInterface) appContext.getBean("fenyeService");
	// }
	 private FenyeSelectInterface getOlympicgamesUpdateInterface() {
	 ApplicationContext appContext = WebApplicationContextUtils
	 .getWebApplicationContext(this.getServlet().getServletContext());
	 return (FenyeSelectInterface) appContext.getBean("fenyeService");
	 }
}
