/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.form;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 11-27-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class ProductUpdateDeleteForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6632181878666790113L;

	/**
	 * 
	 */

	//	 ID
	private Integer fenye_Id;

	// 访问记录
	private Integer fwjilu;

	// 主题
	private String zhuti;

	// 作者
	private String zuozhe;


	public Integer getFwjilu() {
		return fwjilu;
	}

	public void setFwjilu(Integer fwjilu) {
		this.fwjilu = fwjilu;
	}

	public String getZhuti() {
		return zhuti;
	}

	public void setZhuti(String zhuti) {
		try {
			this.zhuti = new String(zhuti.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public String getZuozhe() {
		return zuozhe;
	}

	public void setZuozhe(String zuozhe) {
		try {
			this.zuozhe = new String(zuozhe.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}


	public Integer getFenye_Id() {
		return fenye_Id;
	}

	public void setFenye_Id(Integer fenye_Id) {
		this.fenye_Id = fenye_Id;
	}



}