/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.form;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 11-27-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class ZhuceForm extends ActionForm {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 8891970881303884118L;

	/** password passWord01 */
	private String passWord01;

	/** password property */
	private String passWord;

	/** username property */
	private String userName;

	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getPassWord() {
		return passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		try {
			this.userName = new String(userName.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public String getPassWord01() {
		return passWord01;
	}

	public void setPassWord01(String passWord01) {
		this.passWord01 = passWord01;
	}

}