/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.xinxi_Action.struts.session.SessionService;
import com.xinxi_Action.struts.session.StaticName;
import com.web_interface.fenye.FenyeSelectInterface;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class NewsAction extends Action {

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	private static final Log log = LogFactory.getLog(NewsAction.class);

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		log.debug("---LoginDAO loginCheck---");
		// 设置session判断用户是否成功登陆或者关闭网页后复制url来进行访问
		// 测试页面跳转 成功=OK

		HttpSession session = request.getSession();
		SessionService sessionservice = new SessionService();
		boolean booleanUser = sessionservice.SessionService(session,
				StaticName.USERLOGIN = (String) session.getAttribute("login"));

		if (booleanUser) {
			FenyeSelectInterface updateService = getNewsSelectInterface();
			List internationalnews = updateService.NewsFindSelectAll(
					StaticName.NEWS_FIRST_RESULT, StaticName.NEWS_MAX_RESULTS,
					StaticName.FENYESQL_SHUJU);
			List olympicgames = updateService.OlympicgamesFindSelectAll(
					StaticName.NEWS_FIRST_RESULT, StaticName.NEWS_MAX_RESULTS,
					StaticName.olympicgames_FENYESQL_SHUJU);
			request.setAttribute("internationalnews", internationalnews);
			request.setAttribute("olympicgames", olympicgames);
			return mapping.findForward("index");
		}

		return mapping.findForward("index");

	}

	private FenyeSelectInterface getNewsSelectInterface() {
		ApplicationContext appContext = WebApplicationContextUtils
				.getWebApplicationContext(this.getServlet().getServletContext());
		return (FenyeSelectInterface) appContext.getBean("fenyeService");
	}
}
