/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 12-02-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="fenyelistForm"
 */
public class FenyelistForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3735070709494026193L;

	/*
	 * Generated fields
	 */

	/** next_text property */
	private String next_text;

	/** next property */
	private String next;

	/*
	 * Generated Methods
	 */

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.next = "";
	}

	/**
	 * Returns the next.
	 * 
	 * @return String
	 */
	public String getNext() {
		return next;
	}

	/**
	 * Set the next.
	 * 
	 * @param next
	 *            The next to set
	 */
	public void setNext(String next) {
		this.next = "";
	}

	public String getNext_text() {
		return next_text;
	}

	public void setNext_text(String next_text) {
		this.next_text = next_text;
	}

}