/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xinxi_Action.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * MyEclipse Struts Creation date: 12-05-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="updateeForm"
 */
public class UpdateForm extends ActionForm {



	/**
	 * 
	 */
	private static final long serialVersionUID = 3451567026832785725L;

	private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

	// ID
	private Integer fenye_Id;

	// 访问记录
	private Integer fwjilu;

	// 主题
	private String zhuti;

	// 作者
	private String zuozhe;

	// 文章内容
	private String neigong;

	// 发表时间
	private java.sql.Timestamp shijian;

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}


	public Integer getFwjilu() {
		return fwjilu;
	}

	public void setFwjilu(Integer fwjilu) {
		this.fwjilu = fwjilu;
	}

	public String getNeigong() {
		return neigong;
	}

	public void setNeigong(String neigong) {
		try {
			this.neigong = new String(neigong.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public String getZhuti() {
		return zhuti;
	}

	public void setZhuti(String zhuti) {
		try {
			this.zhuti = new String(zhuti.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public String getZuozhe() {
		return zuozhe;
	}

	public void setZuozhe(String zuozhe) {
		try {
			this.zuozhe = new String(zuozhe.getBytes("ISO-8859-1"), "GBK");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public java.sql.Timestamp getShijian() {
		return shijian;
	}

	public void setShijian(java.sql.Timestamp shijian) {
		this.shijian = shijian;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}


	public SimpleDateFormat getSdf() {
		return sdf;
	}

	public void setSdf(SimpleDateFormat sdf) {
		this.sdf = sdf;
	}

	public Integer getFenye_Id() {
		return fenye_Id;
	}

	public void setFenye_Id(Integer fenye_Id) {
		this.fenye_Id = fenye_Id;
	}
}